Repository redxzeta/Awesome-Adoption, pull requests merged in 2022-10, with the labels that each got.

#435 migrated from heroicons v2 to v3
  package.json
  src/components/layout/FavoriteButton/index.tsx
  src/components/layout/NavigationBar.tsx
  src/components/pets/PetInfo.tsx
  src/components/pets/PetType.tsx
  yarn.lock
Labels: hacktoberfest-accepted

#439 feat: Missing menu in mobile view
  src/components/layout/NavigationBar.tsx
Labels: hacktoberfest-accepted

#436 added refresh button placeholder
  src/components/home/Home.tsx
  src/components/home/home.css
  src/components/home/loding.png
Labels: hacktoberfest-accepted

#441 docs: update readme.md
  README.md
Labels: documentation, hacktoberfest-accepted, Hacktoberfest

#448 fix: make organization cards even
  src/components/organizations/OrganizationsCard.tsx
  src/components/organizations/__tests__/organizations.test.tsx
Labels: hacktoberfest-accepted

#449 fix: updated the workflow
  .github/workflows/greetings.yml
Labels: hacktoberfest-accepted

#463 fix: Fixed Responsiveness in Register tab
  src/components/accounts/Register.tsx
Labels: hacktoberfest-accepted

#456 feat: implemeted dark mode
  src/components/layout/NavigationBar.tsx
  src/components/themeToggle/themeToggle.tsx
  tailwind.config.js
Labels: hacktoberfest-accepted, Hacktoberfest

#434 fix: New placeholder
  src/components/layout/PetCard.tsx
  src/components/pets/PetInfo.tsx
  src/components/pets/Pets.tsx
  src/components/pets/__tests__/pets.test.tsx
  src/components/pets/placeholder-dark.png
  src/components/pets/placeholder-light.png
  src/components/pets/placeholder.jpg
Labels: hacktoberfest-accepted, Hacktoberfest

#469 fix-dark-mode svg issue
  src/components/shared/PetIcon/icons/bird.png
  src/components/shared/PetIcon/icons/bird.svg
  src/components/shared/PetIcon/icons/cat.png
  src/components/shared/PetIcon/icons/cat.svg
  src/components/shared/PetIcon/icons/dog.png
  src/components/shared/PetIcon/icons/dog.svg
  src/components/shared/PetIcon/icons/horse.png
  src/components/shared/PetIcon/icons/horse.svg
  src/components/shared/PetIcon/icons/house.png
  src/components/shared/PetIcon/icons/house.svg
  src/components/shared/PetIcon/icons/rabbit.png
  src/components/shared/PetIcon/icons/rabbit.svg
  src/components/shared/PetIcon/index.tsx
  src/images/icons/bird.png
  src/images/icons/bird.svg
  src/images/icons/cat.png
  src/images/icons/cat.svg
  src/images/icons/dog.png
  src/images/icons/dog.svg
  src/images/icons/horse.png
  src/images/icons/horse.svg
  src/images/icons/house.svg
  src/images/icons/rabbit.png
  src/images/icons/rabbit.svg
Labels: hacktoberfest-accepted

#485 fix: hiding the hamburger menu navigation on lg screens
  src/components/layout/NavigationBar.tsx
Labels: hacktoberfest-accepted

#488 feat: added github url in footer
  src/components/layout/Footer.tsx
Labels: hacktoberfest-accepted

#476 fix: display share based on feature availability
  src/components/pets/PetInfo.tsx
Labels: hacktoberfest-accepted

#489 [Fixed] : footer always in bottom
  src/App.css
Labels: hacktoberfest-accepted

#497 feat: filter on favorite pets added
  src/components/pets/Favorites.tsx
Labels: hacktoberfest-accepted

#502 fix: correct external links
  src/components/about/About.tsx
  src/components/about/Discord.png
Labels: hacktoberfest-accepted

#501 fix: zipcode label overflowing
  src/components/pets/PetType.tsx
Labels: hacktoberfest-accepted

#496 fix: image sizes in the carousel is not equal
  src/App.css
Labels: hacktoberfest-accepted
